---
abstract: 'Test package for script test_app'
author:
  - 'Igor Sverdlov <igor-sverdlov@mail.ru>'
build_requires:
  lib::abs: '0'
configure_requires:
  Module::Build::Tiny: '0.019'
  perl: '5.006'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.010, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TestApp
provides:
  TestApp:
    file: lib/TestApp.pm
    version: v0.0.5
  TestApp::Data:
    file: lib/TestApp/Data.pm
requires:
  Term::ANSIColor: '0'
version: 0.0.6

